### ISSUE TITLE
feature: Loading style file imported

### ISSUE THREAD

**Issue by flingyp** [yue1123/vite-plugin-spa-loading#1]
**Is your feature request related to a problem? Please describe.**

Add a feature that plugin can support custom style file imported. Maybe like svg and img imported.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yue1123** [comment]
good idea! Are you interested in implementing this feature？

**Comment by flingyp** [comment]
OK. Look that on the weekend.

**Comment by yue1123** [comment]
ok
